<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns0="http://TargetNamespace.com/fileService" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbReference" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/file/SOAComplexCsvTest/SOAComplexCsvTest/fileService"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/SOAComplexCsvTest/SOAComplexCsvTest/dbReference">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/fileService.wsdl"/>
            <oracle-xsl-mapper:rootElement name="Root-Element" namespace="http://TargetNamespace.com/fileService"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/dbReference.wsdl"/>
            <oracle-xsl-mapper:rootElement name="XxasfSampleRecord1Collection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbReference"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU APR 06 10:55:48 EDT 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:XxasfSampleRecord1Collection>
         <xsl:for-each select="/ns0:Root-Element/ns0:RECORD1">
            <tns:XxasfSampleRecord1>
               <tns:c2>
                  <xsl:value-of select="ns0:C2"/>
               </tns:c2>
               <tns:c3>
                  <xsl:value-of select="ns0:C3"/>
               </tns:c3>
               <tns:c4>
                  <xsl:value-of select="ns0:C4"/>
               </tns:c4>
               <tns:c5>
                  <xsl:value-of select="ns0:C5"/>
               </tns:c5>
               <tns:c6>
                  <xsl:value-of select="ns0:C6"/>
               </tns:c6>
               <tns:c7>
                  <xsl:value-of select="ns0:C7"/>
               </tns:c7>
               <tns:c8>
                  <xsl:value-of select="ns0:C8"/>
               </tns:c8>
               <tns:c9>
                  <xsl:value-of select="ns0:C9"/>
               </tns:c9>
               <tns:xxasfSampleRecord2Collection>
                  <xsl:for-each select="ns0:RECORD2">
                     <tns:XxasfSampleRecord2>
                        <tns:c2>
                           <xsl:value-of select="ns0:C2"/>
                        </tns:c2>
                        <tns:c3>
                           <xsl:value-of select="ns0:C3"/>
                        </tns:c3>
                        <tns:c4>
                           <xsl:value-of select="ns0:C4"/>
                        </tns:c4>
                        <tns:c5>
                           <xsl:value-of select="ns0:C5"/>
                        </tns:c5>
                        <tns:c6>
                           <xsl:value-of select="ns0:C6"/>
                        </tns:c6>
                        <tns:c7>
                           <xsl:value-of select="ns0:C7"/>
                        </tns:c7>
                        <tns:c8>
                           <xsl:value-of select="ns0:C8"/>
                        </tns:c8>
                        <tns:c9>
                           <xsl:value-of select="ns0:C9"/>
                        </tns:c9>
                        <tns:c10>
                           <xsl:value-of select="ns0:C10"/>
                        </tns:c10>
                     </tns:XxasfSampleRecord2>
                  </xsl:for-each>
               </tns:xxasfSampleRecord2Collection>
            </tns:XxasfSampleRecord1>
         </xsl:for-each>
      </tns:XxasfSampleRecord1Collection>
   </xsl:template>
</xsl:stylesheet>
